[book]
language = "es"
languages = ["en", "es"]
multilingual = true
src = "src"
title = "Rust para C#/.NET Developers"

[language.en]
name = "English"

[language.es]
name = "Spanish"

[output.html]
site-url = "https://dotnet-book.rustlang-es.org"
additional-css = ["ferris.css"]
additional-js = ["ferris.js"]
git-repository-url = "https://github.com/RustLangES/rust-para-dotnet-devs"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/RustLangES/rust-para-dotnet-devs/edit/es-translation/{path}"

[output.html.playground]
runnable = false
