name: Publish to GitHub Pages

on:
  push:
    branches:
      - main
      - es-translation

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: write
      pages: write
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Install mdBook
      run: |
        mkdir mdbook
        curl -sSL https://github.com/RustLangES/mdBook/releases/download/v0.4.3-localization/mdbook-v0.4.3-localization-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=./mdbook
        echo `pwd`/mdbook >> $GITHUB_PATH
    - name: Build
      run: mdbook build --language es
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        name: book
        path: ./book

  # Deployment job
  deploy:
    permissions:
      id-token: write
      pages: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
        with:
          artifact_name: book


